const canvas=document.getElementById('sceneCanvas');
const ctx=canvas.getContext('2d');
const viewport=document.getElementById('viewport');
const toastEl=document.getElementById('toast');
const sceneObjectsEl=document.getElementById('sceneObjects');
const materialPreview=document.getElementById('materialPreview');
const objectName=document.getElementById('objectName');

let showGrid=true, snap=false, perspective=true, playing=false, frame=1, activeId=2;
let camera={yaw:-.35,pitch:.45,zoom:1,panX:0,panY:0};
let pointer=null;
let objects=[
 {id:1,name:'Base',type:'box',x:0,y:0,z:0,w:140,h:10,d:110,color:'#dbe7ee',rot:0},
 {id:2,name:'Hero Cube',type:'box',x:0,y:0,z:20,w:54,h:54,d:54,color:'#5db7ff',rot:0},
 {id:3,name:'Roof',type:'cone',x:0,y:0,z:63,w:72,h:28,d:72,color:'#63d29b',rot:0},
 {id:4,name:'Crown',type:'cylinder',x:0,y:0,z:86,w:22,h:22,d:22,color:'#ffb55e',rot:0}
];
const palettes=['#5db7ff','#63d29b','#ffb55e','#f37e93','#9a8df2','#f4f6f8'];

function resize(){const r=viewport.getBoundingClientRect();const ratio=devicePixelRatio||1;canvas.width=r.width*ratio;canvas.height=r.height*ratio;canvas.style.width=r.width+'px';canvas.style.height=r.height+'px';ctx.setTransform(ratio,0,0,ratio,0,0);render();}
function W(){return canvas.clientWidth||800} function H(){return canvas.clientHeight||600}
function project(x,y,z){const cy=Math.cos(camera.yaw),sy=Math.sin(camera.yaw),cp=Math.cos(camera.pitch),sp=Math.sin(camera.pitch);const a=x*cy-y*sy,b=x*sy+y*cy;const yy=b*cp-z*sp,zz=b*sp+z*cp;return{x:W()/2+(a-camera.panX)*camera.zoom*3.35,y:H()*.58-(yy-camera.panY)*camera.zoom*2.8-zz*camera.zoom*2.8}}
function shade(hex,n){const v=parseInt(hex.slice(1),16);return `rgb(${Math.max(0,Math.min(255,(v>>16)+n))},${Math.max(0,Math.min(255,((v>>8)&255)+n))},${Math.max(0,Math.min(255,(v&255)+n))})`}
function corners(o){const hw=o.w/2,hd=o.d/2,hh=o.h/2,ang=(o.rot||0)*Math.PI/180;return[[-hw,-hd,-hh],[hw,-hd,-hh],[hw,hd,-hh],[-hw,hd,-hh],[-hw,-hd,hh],[hw,-hd,hh],[hw,hd,hh],[-hw,hd,hh]].map(([x,y,z])=>({x:x*Math.cos(ang)-y*Math.sin(ang)+o.x,y:x*Math.sin(ang)+y*Math.cos(ang)+o.y,z:z+o.z+hh}));}
function poly(points,fill,stroke='rgba(35,52,63,.18)',width=1){ctx.beginPath();ctx.moveTo(points[0].x,points[0].y);points.slice(1).forEach(p=>ctx.lineTo(p.x,p.y));ctx.closePath();ctx.fillStyle=fill;ctx.fill();ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke()}
function drawBox(o){const c=corners(o),p=c.map(v=>project(v.x,v.y,v.z));const faces=[[0,1,2,3,16],[0,1,5,4,7],[1,2,6,5,12],[2,3,7,6,-4],[4,5,6,7,-18],[0,3,7,4,0]];faces.sort((a,b)=>b[4]-a[4]).forEach(f=>poly(f.slice(0,4).map(i=>p[i]),shade(o.color,f[4]),o.id===activeId?'#197fe4':'rgba(35,52,63,.18)',o.id===activeId?1.8:1));if(o.id===activeId){ctx.setLineDash([6,4]);poly([p[0],p[1],p[2],p[3],p[7],p[6],p[5],p[4]],'transparent','#197fe4',2);ctx.setLineDash([])}}
function drawCylinder(o){const rings=24,top=[],bottom=[];for(let i=0;i<rings;i++){const a=i/rings*Math.PI*2;top.push(project(o.x+Math.cos(a)*o.w/2,o.y+Math.sin(a)*o.d/2,o.z+o.h));bottom.push(project(o.x+Math.cos(a)*o.w/2,o.y+Math.sin(a)*o.d/2,o.z))}for(let i=0;i<rings;i++)poly([bottom[i],bottom[(i+1)%rings],top[(i+1)%rings],top[i]],shade(o.color,(i<rings/2?9:-2)));poly(top,shade(o.color,18));poly(bottom,shade(o.color,-12));}
function drawSphere(o){const p=project(o.x,o.y,o.z+o.h/2);const r=o.w*camera.zoom*1.4;const g=ctx.createRadialGradient(p.x-r*.3,p.y-r*.4,r*.1,p.x,p.y,r);g.addColorStop(0,'#fff');g.addColorStop(.2,shade(o.color,30));g.addColorStop(1,shade(o.color,-25));ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fillStyle=g;ctx.fill();ctx.strokeStyle=o.id===activeId?'#197fe4':'rgba(35,52,63,.2)';ctx.lineWidth=2;ctx.stroke()}
function drawCone(o){const base=[],tip=project(o.x,o.y,o.z+o.h);for(let i=0;i<24;i++){const a=i/24*Math.PI*2;base.push(project(o.x+Math.cos(a)*o.w/2,o.y+Math.sin(a)*o.d/2,o.z))}for(let i=0;i<24;i++)poly([base[i],base[(i+1)%24],tip],shade(o.color,i<12?12:-4),o.id===activeId?'#197fe4':'rgba(35,52,63,.18)',o.id===activeId?1.7:1);poly(base,shade(o.color,-13))}
function drawTorus(o){const p=project(o.x,o.y,o.z+o.h/2);ctx.beginPath();ctx.ellipse(p.x,p.y,radius(o.w)*1.5,radius(o.d)*.6,0,0,Math.PI*2);ctx.strokeStyle=o.color;ctx.lineWidth=12*camera.zoom;ctx.stroke();ctx.strokeStyle=shade(o.color,-22);ctx.lineWidth=2;ctx.stroke()}
function radius(n){return n*camera.zoom*1.1}
function drawObject(o){if(o.type==='sphere')drawSphere(o);else if(o.type==='cylinder')drawCylinder(o);else if(o.type==='cone')drawCone(o);else if(o.type==='torus')drawTorus(o);else drawBox(o)}
function render(){ctx.clearRect(0,0,W(),H());ctx.fillStyle=document.getElementById('worldColor')?.value||'#edf3f7';ctx.fillRect(0,0,W(),H());if(showGrid){ctx.lineWidth=1;for(let n=-240;n<=240;n+=20){const a=project(n,-240,0),b=project(n,240,0),c=project(-240,n,0),d=project(240,n,0);ctx.strokeStyle='rgba(112,139,152,.16)';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.moveTo(c.x,c.y);ctx.lineTo(d.x,d.y);ctx.stroke()}}if(document.getElementById('groundToggle')?.checked){const a=project(-200,-200,-1),b=project(200,-200,-1),c=project(200,200,-1),d=project(-200,200,-1);poly([a,b,c,d],'rgba(255,255,255,.22)','transparent')}objects.slice().sort((a,b)=>a.z-b.z).forEach(drawObject)}
function active(){return objects.find(o=>o.id===activeId)||objects[0]}
function updateInspector(){const o=active();if(!o)return;objectName.value=o.name;materialPreview.style.background=o.color;['posX','posY','posZ'].forEach((id,i)=>document.getElementById(id).value=[o.x,o.y,o.z][i].toFixed(2));['rotX','rotY','rotZ'].forEach((id,i)=>document.getElementById(id).value=(i===2?o.rot:0)+'°');document.getElementById('widthInput').value=(o.w/10).toFixed(2);document.getElementById('heightInput').value=(o.h/10).toFixed(2);document.getElementById('depthInput').value=(o.d/10).toFixed(2);document.querySelectorAll('.color-swatches button').forEach(b=>b.classList.toggle('active',b.dataset.color.toLowerCase()===o.color.toLowerCase()));renderSceneTree()}
function renderSceneTree(){sceneObjectsEl.innerHTML=objects.map(o=>`<div class="tree-object ${o.id===activeId?'selected':''}" data-id="${o.id}">⌁ &nbsp;${o.name}</div>`).join('');sceneObjectsEl.querySelectorAll('.tree-object').forEach(el=>el.onclick=()=>{activeId=+el.dataset.id;updateInspector()})}
function toast(message){toastEl.textContent=message;toastEl.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>toastEl.classList.remove('show'),1800)}
function addObject(type){const colors={box:'#5db7ff',cylinder:'#63d29b',sphere:'#f37e93',cone:'#ffb55e',torus:'#9a8df2',light:'#fff1c9'};const n=objects.length+1;objects.push({id:Date.now(),name:`${type[0].toUpperCase()+type.slice(1)} ${String(n).padStart(2,'0')}`,type,x:(Math.random()-.5)*40,y:(Math.random()-.5)*40,z:20,w:type==='torus'?44:30,h:type==='sphere'?30:34,d:30,color:colors[type]||'#5db7ff',rot:0});activeId=objects.at(-1).id;updateInspector();toast(`${type} added`)}

document.querySelectorAll('.rail-item').forEach(b=>b.onclick=()=>{document.querySelectorAll('.rail-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');const t=b.dataset.tool;if(['box','cylinder','sphere','cone','torus'].includes(t))addObject(t);else toast(`${t[0].toUpperCase()+t.slice(1)} tool active`)})
document.querySelectorAll('.asset-grid button').forEach(b=>b.onclick=()=>addObject(b.dataset.add));document.querySelectorAll('.color-swatches button').forEach(b=>b.onclick=()=>{active().color=b.dataset.color;updateInspector()});document.getElementById('deleteBtn').onclick=()=>{if(objects.length>1){objects=objects.filter(o=>o.id!==activeId);activeId=objects.at(-1).id;updateInspector();toast('Object deleted')}};document.getElementById('renameProject').onclick=()=>{const n=prompt('Project name',document.getElementById('projectName').textContent);if(n)document.getElementById('projectName').textContent=n};objectName.onchange=()=>{active().name=objectName.value;renderSceneTree()};document.getElementById('gridToggle').onclick=()=>{showGrid=!showGrid;document.getElementById('gridToggle').classList.toggle('active',showGrid);render()};document.getElementById('snapToggle').onclick=()=>{snap=!snap;document.getElementById('snapToggle').querySelector('i').textContent=snap?'ON':'OFF';toast(`Snap ${snap?'enabled':'disabled'}`)};document.getElementById('worldColor').oninput=render;document.getElementById('groundToggle').onchange=render;

document.querySelectorAll('.panel-tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.panel-tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');document.querySelectorAll('.panel-content').forEach(p=>p.classList.add('hidden'));document.getElementById(tab.dataset.panel+'Panel').classList.remove('hidden')});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');toast(`${b.textContent} mode`)})
document.getElementById('addModifier').onclick=()=>toast('Modifier menu opened');document.getElementById('saveBtn').onclick=()=>{localStorage.modelLab=JSON.stringify(objects);toast('Project saved locally')};document.getElementById('undo').onclick=()=>toast('Undo');document.getElementById('redo').onclick=()=>toast('Redo');document.getElementById('fullscreenBtn').onclick=()=>document.documentElement.requestFullscreen?.();document.getElementById('cameraToggle').onclick=()=>{perspective=!perspective;document.getElementById('cameraToggle').textContent=perspective?'Perspective':'Orthographic';toast(document.getElementById('cameraToggle').textContent)};document.getElementById('focusBtn').onclick=()=>{camera.zoom=1;camera.panX=0;camera.panY=0;render()};document.getElementById('homeView').onclick=()=>{camera={yaw:-.35,pitch:.45,zoom:1,panX:0,panY:0};render()};document.getElementById('viewFront').onclick=()=>{camera.yaw=0;camera.pitch=0;render()};document.getElementById('viewTop').onclick=()=>{camera.yaw=0;camera.pitch=1.48;render()};document.getElementById('viewSide').onclick=()=>{camera.yaw=1.57;camera.pitch=0;render()};document.getElementById('playBtn').onclick=()=>{playing=!playing;document.getElementById('playBtn').textContent=playing?'Ⅱ':'▶';toast(playing?'Animation playing':'Animation paused')};document.getElementById('timelineRange').oninput=e=>{frame=e.target.value};

canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect();pointer={x:e.clientX,y:e.clientY,yaw:camera.yaw,pitch:camera.pitch,panX:camera.panX,panY:camera.panY,shift:e.shiftKey};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!pointer)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y;if(e.shiftKey||pointer.shift){camera.panX=pointer.panX-dx/12;camera.panY=pointer.panY+dy/12}else{camera.yaw=pointer.yaw-dx*.008;camera.pitch=Math.max(-1.2,Math.min(1.2,pointer.pitch-dy*.008))}render()});canvas.addEventListener('pointerup',()=>pointer=null);canvas.addEventListener('wheel',e=>{e.preventDefault();camera.zoom=Math.max(.45,Math.min(2.2,camera.zoom*(e.deltaY>0?.9:1.1)));render()},{passive:false});

setInterval(()=>{if(playing){frame=frame>=120?1:frame+1;document.getElementById('timelineRange').value=frame;active().rot=(frame-1)*3;render()}},80);window.addEventListener('resize',resize);updateInspector();resize();
